name: household-saving-rate-analysis
channels:
  - defaults
  - conda-forge
  - pytorch
  - plotly
  # - fastai
dependencies:
  - python>=3.6
  - pip
  # BASICS
  - numpy
  - scipy
  - pandas
  - tqdm
  - click
  - ipython
  # VISUALIZATION
  - matplotlib
  - ipympl  # interactive matplotlib plots
  - seaborn
  # - altair
  # - yellowbrick
  # ML, STATS & DEEP LEARNING
  - statsmodels
  - scikit-learn
  - plotly
  # - sktime
  # - tslearn
  # - xgboost
  # - catboost
  # - lightgbm
  # - pytorch
  # - fastai  # activate fastai channel above!
  # - tensorflow
  # - keras
  # - spacy

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - jupyterlab